export class Character{
    id:number;
    player:number;
    character_name:string;
    my_class:number;
    my_race:number;
    class_prof1:number;
    class_prof2:number;
    background:number;
    gear:string;
    equiped_ac:number;
    personality:string;
    ideals:string;
    bonds:string;
    flaws:string;
    appearance:string;
    allies:string;
    tempdata:number;
}